let sendtoPDF = document.getElementById('sendtoPDF');
let numbering = document.getElementById('numbering');
let clearall = document.getElementById('clearall');
let qtable = document.querySelector('.questionstable');
let qlist = document.querySelector('.questionlist-table');
let qtablewrapper = document.querySelector('.qtable-wrapper');
let insertallquestions = document.getElementById('insertallquestions');
let chapter = document.querySelectorAll(".chapter");
let gradesbtn = document.querySelectorAll(".gradesbtn");
let questionlistwrapper = document.querySelector(".questionlist-wrapper");
let npages = document.querySelector('.npagesvalue');
let inputwrapper = document.querySelectorAll('.inputwrapper');
let inputs = document.querySelectorAll('.inputs');
let selectedgrade = document.querySelector('.selectedgrade');
let selectedchapter = document.querySelector('.selectedchapter');
let dropdownwrapper = document.querySelectorAll('.dropdown-wrapper');
let dropdowncontent = document.querySelectorAll('.dropdown-content');
let headerlowerelements = document.querySelector('.header-lower-elements');
let main = document.querySelector('.main');
var questionstable = document.querySelector('.questionstable');
var marks = document.querySelectorAll('.marks');
var markinput = document.querySelectorAll('.markinput');
var nums = document.getElementsByClassName('questionnumber');
var kl=0;

function set_sum(){
   let sumofmarks=document.querySelector('.sumofmarks');
   let markinput = document.querySelectorAll('.markinput');
   kl=0;
    for (i = 0; i < markinput.length; i++){
        if (markinput[i].value==""){
            kl+=0;
        }
        else{
            kl+= parseFloat(markinput[i].value);
        }
    }
    if (isNaN(kl)){
        sumofmarks.innerHTML="";
    }
    else{
       sumofmarks.innerHTML=kl;
    }
}

qtablewrapper.addEventListener('mouseover', function(){
    set_sum();
});


for (let i = 0; i < dropdowncontent.length; i++) {
    dropdowncontent[i].addEventListener('click', function () {
        dropdowncontent[i].style.visibility = 'hidden';
        dropdowncontent[i].style.opacity = '0';
        dropdowncontent[i].style.transition= 'all 1s ease';

    });
}
for (let i = 0; i < dropdownwrapper.length; i++) {
    dropdownwrapper[i].addEventListener('mouseover', function () {
        dropdowncontent[i].style.visibility = 'visible';
        dropdowncontent[i].style.opacity = '1';
        dropdowncontent[i].style.transition= 'all 1s ease';
    });
}
for (let i = 0; i < dropdownwrapper.length; i++) {
    dropdownwrapper[i].addEventListener('mouseleave', function () {
        dropdowncontent[i].style.visibility = 'hidden';
        dropdowncontent[i].style.opacity = '0';
        dropdowncontent[i].style.transition= 'all 0.5s ease';
    });
}


let mathsource = [
    [//کتاب ریاضی هفتم
    [//فصل اول
    './images/math/7/ch1/1.png',
    './images/math/7/ch1/2.png',
    './images/math/7/ch1/3.png',
    './images/math/7/ch1/4.png',
    './images/math/7/ch1/5.png',
    './images/math/7/ch1/6.png',
    './images/math/7/ch1/7.png',
    './images/math/7/ch1/8.png',
    './images/math/7/ch1/9.png',
    './images/math/7/ch1/10.png',
    './images/math/7/ch1/11.png',
    './images/math/7/ch1/12.png',
    './images/math/7/ch1/13.png',
    './images/math/7/ch1/14.png',
    './images/math/7/ch1/15.png',
    './images/math/7/ch1/16.png',
    './images/math/7/ch1/17.png',
    './images/math/7/ch1/18.png',
    './images/math/7/ch1/19.png',
    './images/math/7/ch1/20.png',
    './images/math/7/ch1/21.png',
    './images/math/7/ch1/22.png',
    './images/math/7/ch1/23.png',
    './images/math/7/ch1/24.png',
    './images/math/7/ch1/25.png',
    './images/math/7/ch1/26.png',
    './images/math/7/ch1/27.png',
    './images/math/7/ch1/28.png',
    './images/math/7/ch1/29.png',
    './images/math/7/ch1/30.png',], //ch1 is completed
[   //فصل دوم
    './images/math/7/ch2/1.png',
    './images/math/7/ch2/2.png',
    './images/math/7/ch2/3.png',
    './images/math/7/ch2/4.png',
    './images/math/7/ch2/5.png',
    './images/math/7/ch2/6.png',
    './images/math/7/ch2/7.png',
    './images/math/7/ch2/8.png',
    './images/math/7/ch2/9.png',
    './images/math/7/ch2/10.png',
    './images/math/7/ch2/11.png',
    './images/math/7/ch2/12.png',
    './images/math/7/ch2/13.png',
    './images/math/7/ch2/14.png',
    './images/math/7/ch2/15.png',
    './images/math/7/ch2/16.png',
    './images/math/7/ch2/17.png',
    './images/math/7/ch2/18.png',
    './images/math/7/ch2/19.png',
    './images/math/7/ch2/20.png',
    './images/math/7/ch2/21.png',
    './images/math/7/ch2/22.png',
    './images/math/7/ch2/23.png',
    './images/math/7/ch2/24.png',
    './images/math/7/ch2/25.png',
    './images/math/7/ch2/26.png',
    './images/math/7/ch2/27.png',
    './images/math/7/ch2/28.png',
    './images/math/7/ch2/29.png',
    './images/math/7/ch2/30.png',
    './images/math/7/ch2/31.png',
    './images/math/7/ch2/32.png',
    './images/math/7/ch2/33.png',
    './images/math/7/ch2/34.png',
    './images/math/7/ch2/35.png',
    './images/math/7/ch2/36.png',
    './images/math/7/ch2/37.png',
    './images/math/7/ch2/38.png',
    './images/math/7/ch2/39.png',
    './images/math/7/ch2/40.png',
    './images/math/7/ch2/41.png',
    './images/math/7/ch2/42.png',
    './images/math/7/ch2/43.png',
    './images/math/7/ch2/44.png',
    './images/math/7/ch2/45.png',
    './images/math/7/ch2/46.png',
    './images/math/7/ch2/47.png',
    './images/math/7/ch2/48.png',
    './images/math/7/ch2/49.png',
    './images/math/7/ch2/50.png',], //ch2 is completed
[   //فصل سوم
    './images/math/7/ch3/1.png',
    './images/math/7/ch3/2.png',
    './images/math/7/ch3/3.png',
    './images/math/7/ch3/4.png',
    './images/math/7/ch3/5.png',
    './images/math/7/ch3/6.png',
    './images/math/7/ch3/7.png',
    './images/math/7/ch3/8.png',
    './images/math/7/ch3/9.png',
    './images/math/7/ch3/10.png',
    './images/math/7/ch3/11.png',
    './images/math/7/ch3/12.png',
    './images/math/7/ch3/13.png',
    './images/math/7/ch3/14.png',
    './images/math/7/ch3/15.png',
    './images/math/7/ch3/16.png',
    './images/math/7/ch3/17.png',
    './images/math/7/ch3/18.png',
    './images/math/7/ch3/19.png',
    './images/math/7/ch3/20.png',
    './images/math/7/ch3/21.png',
    './images/math/7/ch3/22.png',
    './images/math/7/ch3/23.png',
    './images/math/7/ch3/24.png',
    './images/math/7/ch3/25.png',
    './images/math/7/ch3/26.png',
    './images/math/7/ch3/27.png',
    './images/math/7/ch3/28.png',
    './images/math/7/ch3/29.png',
    './images/math/7/ch3/30.png',
    './images/math/7/ch3/31.png',
    './images/math/7/ch3/32.png',
    './images/math/7/ch3/33.png',
    './images/math/7/ch3/34.png',
    './images/math/7/ch3/35.png',
    './images/math/7/ch3/36.png',
    './images/math/7/ch3/37.png',
    './images/math/7/ch3/38.png',
    './images/math/7/ch3/39.png',
    './images/math/7/ch3/40.png',
    './images/math/7/ch3/41.png',
    './images/math/7/ch3/42.png',
    './images/math/7/ch3/43.png',
    './images/math/7/ch3/44.png',
    './images/math/7/ch3/45.png',
    './images/math/7/ch3/46.png',
    './images/math/7/ch3/47.png',
    './images/math/7/ch3/48.png',
    './images/math/7/ch3/49.png',
    './images/math/7/ch3/50.png',
    './images/math/7/ch3/51.png',
    './images/math/7/ch3/52.png',
    './images/math/7/ch3/53.png',
    './images/math/7/ch3/54.png',
    './images/math/7/ch3/55.png',], //ch3 is completed
[//فصل چهارم
    './images/math/7/ch4/1.png',
    './images/math/7/ch4/2.png',
    './images/math/7/ch4/3.png',
    './images/math/7/ch4/4.png',
    './images/math/7/ch4/5.png',
    './images/math/7/ch4/6.png',
    './images/math/7/ch4/7.png',
    './images/math/7/ch4/8.png',
    './images/math/7/ch4/9.png',
    './images/math/7/ch4/10.png',
    './images/math/7/ch4/11.png',
    './images/math/7/ch4/12.png',
    './images/math/7/ch4/13.png',
    './images/math/7/ch4/14.png',
    './images/math/7/ch4/15.png',
    './images/math/7/ch4/16.png',
    './images/math/7/ch4/17.png',
    './images/math/7/ch4/18.png',
    './images/math/7/ch4/19.png',
    './images/math/7/ch4/20.png',
    './images/math/7/ch4/21.png',
    './images/math/7/ch4/22.png',
    './images/math/7/ch4/23.png',
    './images/math/7/ch4/24.png',
    './images/math/7/ch4/25.png',
    './images/math/7/ch4/26.png',
    './images/math/7/ch4/27.png',
    './images/math/7/ch4/28.png',
    './images/math/7/ch4/29.png',
    './images/math/7/ch4/30.png',
    './images/math/7/ch4/31.png',
    './images/math/7/ch4/32.png',
    './images/math/7/ch4/33.png',
    './images/math/7/ch4/34.png',], // ch4 is completed
[//فصل پنجم
    './images/math/7/ch5/1.png',
    './images/math/7/ch5/2.png',
    './images/math/7/ch5/3.png',
    './images/math/7/ch5/4.png',
    './images/math/7/ch5/5.png',
    './images/math/7/ch5/6.png',
    './images/math/7/ch5/7.png',
    './images/math/7/ch5/8.png',
    './images/math/7/ch5/9.png',
    './images/math/7/ch5/10.png',
    './images/math/7/ch5/11.png',
    './images/math/7/ch5/12.png',
    './images/math/7/ch5/13.png',
    './images/math/7/ch5/14.png',
    './images/math/7/ch5/15.png',
    './images/math/7/ch5/16.png',
    './images/math/7/ch5/17.png',
    './images/math/7/ch5/18.png',
    './images/math/7/ch5/19.png',
    './images/math/7/ch5/20.png',
    './images/math/7/ch5/21.png',
    './images/math/7/ch5/22.png',
    './images/math/7/ch5/23.png',
    './images/math/7/ch5/24.png',
    './images/math/7/ch5/25.png',
    './images/math/7/ch5/26.png',
    './images/math/7/ch5/27.png',
    './images/math/7/ch5/28.png',
    './images/math/7/ch5/29.png',
    './images/math/7/ch5/30.png',
    './images/math/7/ch5/31.png',
    './images/math/7/ch5/32.png',
    './images/math/7/ch5/33.png',
    './images/math/7/ch5/34.png',
    './images/math/7/ch5/35.png',
    './images/math/7/ch5/36.png',
    './images/math/7/ch5/37.png',
    './images/math/7/ch5/38.png',
    './images/math/7/ch5/39.png',
    './images/math/7/ch5/40.png',
    './images/math/7/ch5/41.png',
    './images/math/7/ch5/42.png',
    './images/math/7/ch5/43.png',
    './images/math/7/ch5/44.png',
    './images/math/7/ch5/45.png',
    './images/math/7/ch5/46.png',
    './images/math/7/ch5/47.png',
    './images/math/7/ch5/48.png',
    './images/math/7/ch5/49.png',
    './images/math/7/ch5/50.png',
    './images/math/7/ch5/51.png',
    './images/math/7/ch5/52.png',
    './images/math/7/ch5/53.png',
    './images/math/7/ch5/54.png',], //ch5 is completed
[//فصل ششم
    './images/math/7/ch6/1.png',
    './images/math/7/ch6/2.png',
    './images/math/7/ch6/3.png',
    './images/math/7/ch6/4.png',
    './images/math/7/ch6/5.png',
    './images/math/7/ch6/6.png',
    './images/math/7/ch6/7.png',
    './images/math/7/ch6/8.png',
    './images/math/7/ch6/9.png',
    './images/math/7/ch6/10.png',
    './images/math/7/ch6/11.png',
    './images/math/7/ch6/12.png',
    './images/math/7/ch6/13.png',
    './images/math/7/ch6/14.png',
    './images/math/7/ch6/15.png',
    './images/math/7/ch6/16.png',
    './images/math/7/ch6/17.png',
    './images/math/7/ch6/18.png',
    './images/math/7/ch6/19.png',
    './images/math/7/ch6/20.png',
    './images/math/7/ch6/21.png',
    './images/math/7/ch6/22.png',
    './images/math/7/ch6/23.png',
    './images/math/7/ch6/24.png',
    './images/math/7/ch6/25.png',
    './images/math/7/ch6/26.png',
    './images/math/7/ch6/27.png',
    './images/math/7/ch6/28.png',
    './images/math/7/ch6/29.png',
    './images/math/7/ch6/30.png',
    './images/math/7/ch6/31.png',
    './images/math/7/ch6/32.png',
    './images/math/7/ch6/33.png',
    './images/math/7/ch6/34.png',
    './images/math/7/ch6/35.png',
    './images/math/7/ch6/36.png',
    './images/math/7/ch6/37.png',
    './images/math/7/ch6/38.png',
    './images/math/7/ch6/39.png',
    './images/math/7/ch6/40.png',
    './images/math/7/ch6/41.png',
    './images/math/7/ch6/42.png',
    './images/math/7/ch6/43.png',
    './images/math/7/ch6/44.png',
    './images/math/7/ch6/45.png',
    './images/math/7/ch6/46.png',], //ch6 is completed
[//فصل هفتم
    './images/math/7/ch7/1.png',
    './images/math/7/ch7/2.png',
    './images/math/7/ch7/3.png',
    './images/math/7/ch7/4.png',
    './images/math/7/ch7/5.png',
    './images/math/7/ch7/6.png',
    './images/math/7/ch7/7.png',
    './images/math/7/ch7/8.png',
    './images/math/7/ch7/9.png',
    './images/math/7/ch7/10.png',
    './images/math/7/ch7/11.png',
    './images/math/7/ch7/12.png',
    './images/math/7/ch7/13.png',
    './images/math/7/ch7/14.png',
    './images/math/7/ch7/15.png',
    './images/math/7/ch7/16.png',
    './images/math/7/ch7/17.png',
    './images/math/7/ch7/18.png',
    './images/math/7/ch7/19.png',
    './images/math/7/ch7/20.png',
    './images/math/7/ch7/21.png',
    './images/math/7/ch7/22.png',
    './images/math/7/ch7/23.png',
    './images/math/7/ch7/24.png',
    './images/math/7/ch7/25.png',
    './images/math/7/ch7/26.png',
    './images/math/7/ch7/27.png',
    './images/math/7/ch7/28.png',
    './images/math/7/ch7/29.png',
    './images/math/7/ch7/30.png',
    './images/math/7/ch7/31.png',
    './images/math/7/ch7/32.png',
    './images/math/7/ch7/33.png',
    './images/math/7/ch7/34.png',
    './images/math/7/ch7/35.png',
    './images/math/7/ch7/36.png',
    './images/math/7/ch7/37.png',
    './images/math/7/ch7/38.png',
    './images/math/7/ch7/39.png',
    './images/math/7/ch7/40.png',
    './images/math/7/ch7/41.png',
    './images/math/7/ch7/42.png',
    './images/math/7/ch7/43.png',
    './images/math/7/ch7/44.png',
    './images/math/7/ch7/45.png',
    './images/math/7/ch7/46.png',
    './images/math/7/ch7/47.png',
    './images/math/7/ch7/48.png',
    './images/math/7/ch7/49.png',], //ch7 is completed. 
[//فصل هشتم
    './images/math/7/ch8/1.png',
    './images/math/7/ch8/2.png',
    './images/math/7/ch8/3.png',
    './images/math/7/ch8/4.png',
    './images/math/7/ch8/5.png',
    './images/math/7/ch8/6.png',
    './images/math/7/ch8/7.png',
    './images/math/7/ch8/8.png',
    './images/math/7/ch8/9.png',
    './images/math/7/ch8/10.png',
    './images/math/7/ch8/11.png',
    './images/math/7/ch8/12.png',
    './images/math/7/ch8/13.png',
    './images/math/7/ch8/14.png',
    './images/math/7/ch8/15.png',
    './images/math/7/ch8/16.png',
    './images/math/7/ch8/17.png',
    './images/math/7/ch8/18.png',
    './images/math/7/ch8/19.png',
    './images/math/7/ch8/20.png',
    './images/math/7/ch8/21.png',
    './images/math/7/ch8/22.png',
    './images/math/7/ch8/23.png',
    './images/math/7/ch8/24.png',
    './images/math/7/ch8/25.png',
    './images/math/7/ch8/26.png',
    './images/math/7/ch8/27.png',
    './images/math/7/ch8/28.png',
    './images/math/7/ch8/29.png',
    './images/math/7/ch8/30.png',
    './images/math/7/ch8/31.png',
    './images/math/7/ch8/32.png',
    './images/math/7/ch8/33.png',
    './images/math/7/ch8/34.png',
    './images/math/7/ch8/35.png',], //ch8 is completed.
[//فصل نهم
    './images/math/7/ch9/1.png',
    './images/math/7/ch9/2.png',
    './images/math/7/ch9/3.png',
    './images/math/7/ch9/4.png',
    './images/math/7/ch9/5.png',
    './images/math/7/ch9/6.png',
    './images/math/7/ch9/7.png',
    './images/math/7/ch9/8.png',
    './images/math/7/ch9/9.png',
    './images/math/7/ch9/10.png',
    './images/math/7/ch9/11.png',
    './images/math/7/ch9/12.png',
    './images/math/7/ch9/13.png',
    './images/math/7/ch9/14.png',
    './images/math/7/ch9/15.png',
    './images/math/7/ch9/16.png',
    './images/math/7/ch9/17.png',
    './images/math/7/ch9/18.png',
    './images/math/7/ch9/19.png',
    './images/math/7/ch9/20.png',
    './images/math/7/ch9/21.png',
    './images/math/7/ch9/22.png',] //ch9 is completed.
],//پایان کتاب هفتم

[//کتاب ریاضی هشتم

    [  //فصل اول
        './images/math/8/ch1/1.png',
        './images/math/8/ch1/2.png',
        './images/math/8/ch1/3.png',
        './images/math/8/ch1/4.png',
        './images/math/8/ch1/5.png',
        './images/math/8/ch1/6.png',
        './images/math/8/ch1/7.png',
        './images/math/8/ch1/8.png',
        './images/math/8/ch1/9.png',
        './images/math/8/ch1/10.png',
        './images/math/8/ch1/11.png',
        './images/math/8/ch1/12.png',
        './images/math/8/ch1/13.png',
        './images/math/8/ch1/14.png',
        './images/math/8/ch1/15.png',
        './images/math/8/ch1/16.png',
        './images/math/8/ch1/17.png',
        './images/math/8/ch1/18.png',
        './images/math/8/ch1/19.png',
        './images/math/8/ch1/20.png',
        './images/math/8/ch1/21.png',
        './images/math/8/ch1/22.png',
        './images/math/8/ch1/23.png',
        './images/math/8/ch1/24.png',
        './images/math/8/ch1/25.png',
        './images/math/8/ch1/26.png',
        './images/math/8/ch1/27.png',
        './images/math/8/ch1/28.png',
        './images/math/8/ch1/29.png',
        './images/math/8/ch1/30.png',
        './images/math/8/ch1/31.png',
        './images/math/8/ch1/32.png',
        './images/math/8/ch1/33.png',
        './images/math/8/ch1/34.png',
        './images/math/8/ch1/35.png',
        './images/math/8/ch1/36.png',
        './images/math/8/ch1/37.png',
        './images/math/8/ch1/38.png',
        './images/math/8/ch1/39.png',
        './images/math/8/ch1/40.png',
        './images/math/8/ch1/41.png',
        './images/math/8/ch1/42.png',
        './images/math/8/ch1/43.png',
        './images/math/8/ch1/44.png',
        './images/math/8/ch1/45.png',
        './images/math/8/ch1/46.png',
        './images/math/8/ch1/47.png',
        './images/math/8/ch1/48.png',
        './images/math/8/ch1/49.png',
        './images/math/8/ch1/50.png',
        './images/math/8/ch1/51.png',
        './images/math/8/ch1/52.png',], //ch1 is completed
    [//فصل دوم
        './images/math/8/ch2/1.png',
        './images/math/8/ch2/2.png',
        './images/math/8/ch2/3.png',
        './images/math/8/ch2/4.png',
        './images/math/8/ch2/5.png',
        './images/math/8/ch2/6.png',
        './images/math/8/ch2/7.png',
        './images/math/8/ch2/8.png',
        './images/math/8/ch2/9.png',
        './images/math/8/ch2/10.png',
        './images/math/8/ch2/11.png',
        './images/math/8/ch2/12.png',
        './images/math/8/ch2/13.png',
        './images/math/8/ch2/14.png',
        './images/math/8/ch2/15.png',
        './images/math/8/ch2/16.png',
        './images/math/8/ch2/17.png',
        './images/math/8/ch2/18.png',
        './images/math/8/ch2/19.png',], //ch2 is completed
    [//فصل سوم
        './images/math/8/ch3/1.png',
        './images/math/8/ch3/2.png',
        './images/math/8/ch3/3.png',
        './images/math/8/ch3/4.png',
        './images/math/8/ch3/5.png',
        './images/math/8/ch3/6.png',
        './images/math/8/ch3/7.png',
        './images/math/8/ch3/8.png',
        './images/math/8/ch3/9.png',
        './images/math/8/ch3/10.png',
        './images/math/8/ch3/11.png',
        './images/math/8/ch3/12.png',
        './images/math/8/ch3/13.png',
        './images/math/8/ch3/14.png',
        './images/math/8/ch3/15.png',
        './images/math/8/ch3/16.png',
        './images/math/8/ch3/17.png',
        './images/math/8/ch3/18.png',
        './images/math/8/ch3/19.png',
        './images/math/8/ch3/20.png',
        './images/math/8/ch3/21.png',
        './images/math/8/ch3/22.png',
        './images/math/8/ch3/23.png',
        './images/math/8/ch3/24.png',
        './images/math/8/ch3/25.png',
        './images/math/8/ch3/26.png',
        './images/math/8/ch3/27.png',
        './images/math/8/ch3/28.png',
        './images/math/8/ch3/29.png',
        './images/math/8/ch3/30.png',
        './images/math/8/ch3/31.png',
        './images/math/8/ch3/32.png',
        './images/math/8/ch3/33.png',
        './images/math/8/ch3/34.png',
        './images/math/8/ch3/35.png',
        './images/math/8/ch3/36.png',
        './images/math/8/ch3/37.png',
        './images/math/8/ch3/38.png',
        './images/math/8/ch3/39.png',
        './images/math/8/ch3/40.png',], //ch3 is completed
    [//فصل چهارم
        './images/math/8/ch4/1.png',
        './images/math/8/ch4/2.png',
        './images/math/8/ch4/3.png',
        './images/math/8/ch4/4.png',
        './images/math/8/ch4/5.png',
        './images/math/8/ch4/6.png',
        './images/math/8/ch4/7.png',
        './images/math/8/ch4/8.png',
        './images/math/8/ch4/9.png',
        './images/math/8/ch4/10.png',
        './images/math/8/ch4/11.png',
        './images/math/8/ch4/12.png',
        './images/math/8/ch4/13.png',
        './images/math/8/ch4/14.png',
        './images/math/8/ch4/15.png',
        './images/math/8/ch4/16.png',
        './images/math/8/ch4/17.png',
        './images/math/8/ch4/18.png',
        './images/math/8/ch4/19.png',
        './images/math/8/ch4/20.png',
        './images/math/8/ch4/21.png',
        './images/math/8/ch4/22.png',
        './images/math/8/ch4/23.png',
        './images/math/8/ch4/24.png',
        './images/math/8/ch4/25.png',
        './images/math/8/ch4/26.png',
        './images/math/8/ch4/27.png',
        './images/math/8/ch4/28.png',
        './images/math/8/ch4/29.png',
        './images/math/8/ch4/30.png',
        './images/math/8/ch4/31.png',
        './images/math/8/ch4/32.png',
        './images/math/8/ch4/33.png',
        './images/math/8/ch4/34.png',
        './images/math/8/ch4/35.png',
        './images/math/8/ch4/36.png',
        './images/math/8/ch4/37.png',
        './images/math/8/ch4/38.png',
        './images/math/8/ch4/39.png',
        './images/math/8/ch4/40.png',
        './images/math/8/ch4/41.png',
        './images/math/8/ch4/42.png',
        './images/math/8/ch4/43.png',
        './images/math/8/ch4/44.png',
        './images/math/8/ch4/45.png',
        './images/math/8/ch4/46.png',
        './images/math/8/ch4/47.png',
        './images/math/8/ch4/48.png',
        './images/math/8/ch4/49.png',
        './images/math/8/ch4/50.png',
        './images/math/8/ch4/51.png',
        './images/math/8/ch4/52.png',
        './images/math/8/ch4/53.png',
        './images/math/8/ch4/54.png',
        './images/math/8/ch4/55.png',
        './images/math/8/ch4/56.png',
        './images/math/8/ch4/57.png',
        './images/math/8/ch4/58.png',
        './images/math/8/ch4/59.png',
        './images/math/8/ch4/60.png',
        './images/math/8/ch4/61.png',
        './images/math/8/ch4/62.png',], //ch4 is completed
    [//فصل پنجم
        './images/math/8/ch5/1.png',
        './images/math/8/ch5/2.png',
        './images/math/8/ch5/3.png',
        './images/math/8/ch5/4.png',
        './images/math/8/ch5/5.png',
        './images/math/8/ch5/6.png',
        './images/math/8/ch5/7.png',
        './images/math/8/ch5/8.png',
        './images/math/8/ch5/9.png',
        './images/math/8/ch5/10.png',
        './images/math/8/ch5/11.png',
        './images/math/8/ch5/12.png',
        './images/math/8/ch5/13.png',
        './images/math/8/ch5/14.png',
        './images/math/8/ch5/15.png',
        './images/math/8/ch5/16.png',
        './images/math/8/ch5/17.png',
        './images/math/8/ch5/18.png',
        './images/math/8/ch5/19.png',
        './images/math/8/ch5/20.png',
        './images/math/8/ch5/21.png',
        './images/math/8/ch5/22.png',
        './images/math/8/ch5/23.png',
        './images/math/8/ch5/24.png',
        './images/math/8/ch5/25.png',
        './images/math/8/ch5/26.png',
        './images/math/8/ch5/27.png',
        './images/math/8/ch5/28.png',
        './images/math/8/ch5/29.png',
        './images/math/8/ch5/30.png',
        './images/math/8/ch5/31.png',
        './images/math/8/ch5/32.png',
        './images/math/8/ch5/33.png',
        './images/math/8/ch5/34.png',
        './images/math/8/ch5/35.png',
        './images/math/8/ch5/36.png',], //ch5 is completed
    [//فصل ششم
        './images/math/8/ch6/1.png',
        './images/math/8/ch6/2.png',
        './images/math/8/ch6/3.png',
        './images/math/8/ch6/4.png',
        './images/math/8/ch6/5.png',
        './images/math/8/ch6/6.png',
        './images/math/8/ch6/7.png',
        './images/math/8/ch6/8.png',
        './images/math/8/ch6/9.png',
        './images/math/8/ch6/10.png',
        './images/math/8/ch6/11.png',
        './images/math/8/ch6/12.png',
        './images/math/8/ch6/13.png',
        './images/math/8/ch6/14.png',
        './images/math/8/ch6/15.png',
        './images/math/8/ch6/16.png',
        './images/math/8/ch6/17.png',
        './images/math/8/ch6/18.png',
        './images/math/8/ch6/19.png',], //ch6 is completed.
    [//فصل هفتم
        './images/math/8/ch7/1.png',
        './images/math/8/ch7/2.png',
        './images/math/8/ch7/3.png',
        './images/math/8/ch7/4.png',
        './images/math/8/ch7/5.png',
        './images/math/8/ch7/6.png',
        './images/math/8/ch7/7.png',
        './images/math/8/ch7/8.png',
        './images/math/8/ch7/9.png',
        './images/math/8/ch7/10.png',
        './images/math/8/ch7/11.png',
        './images/math/8/ch7/12.png',
        './images/math/8/ch7/13.png',
        './images/math/8/ch7/14.png',
        './images/math/8/ch7/15.png',
        './images/math/8/ch7/16.png',
        './images/math/8/ch7/17.png',
        './images/math/8/ch7/18.png',
        './images/math/8/ch7/19.png',
        './images/math/8/ch7/20.png',
        './images/math/8/ch7/21.png',
        './images/math/8/ch7/22.png',
        './images/math/8/ch7/23.png',
        './images/math/8/ch7/24.png',
        './images/math/8/ch7/25.png',
        './images/math/8/ch7/26.png',
        './images/math/8/ch7/27.png',
        './images/math/8/ch7/28.png',
        './images/math/8/ch7/29.png',
        './images/math/8/ch7/30.png',
        './images/math/8/ch7/31.png',
        './images/math/8/ch7/32.png',
        './images/math/8/ch7/33.png',
        './images/math/8/ch7/34.png',
        './images/math/8/ch7/35.png',
        './images/math/8/ch7/36.png',
        './images/math/8/ch7/37.png',
        './images/math/8/ch7/38.png',
        './images/math/8/ch7/39.png',
        './images/math/8/ch7/40.png',
        './images/math/8/ch7/41.png',
        './images/math/8/ch7/42.png',
        './images/math/8/ch7/43.png',
        './images/math/8/ch7/44.png',
        './images/math/8/ch7/45.png',
        './images/math/8/ch7/46.png',
        './images/math/8/ch7/47.png',], //ch7 is completed.
    [//فصل هشتم
        './images/math/8/ch8/1.png',
        './images/math/8/ch8/2.png',
        './images/math/8/ch8/3.png',
        './images/math/8/ch8/4.png',
        './images/math/8/ch8/5.png',
        './images/math/8/ch8/6.png',
        './images/math/8/ch8/7.png',
        './images/math/8/ch8/8.png',
        './images/math/8/ch8/9.png',
        './images/math/8/ch8/10.png',
        './images/math/8/ch8/11.png',
        './images/math/8/ch8/12.png',
        './images/math/8/ch8/13.png',
        './images/math/8/ch8/14.png',
        './images/math/8/ch8/15.png',
        './images/math/8/ch8/16.png',
        './images/math/8/ch8/17.png',
        './images/math/8/ch8/18.png',
        './images/math/8/ch8/19.png',
        './images/math/8/ch8/20.png',], //ch8 is completed.
    [//فصل نهم
        './images/math/8/ch9/1.png',
        './images/math/8/ch9/2.png',
        './images/math/8/ch9/3.png',
        './images/math/8/ch9/4.png',
        './images/math/8/ch9/5.png',
        './images/math/8/ch9/6.png',
        './images/math/8/ch9/7.png',
        './images/math/8/ch9/8.png',
        './images/math/8/ch9/9.png',
        './images/math/8/ch9/10.png',
        './images/math/8/ch9/11.png',
        './images/math/8/ch9/12.png',
        './images/math/8/ch9/13.png',
        './images/math/8/ch9/14.png',
        './images/math/8/ch9/15.png',
        './images/math/8/ch9/16.png',
        './images/math/8/ch9/17.png',
        './images/math/8/ch9/18.png',
        './images/math/8/ch9/19.png',
        './images/math/8/ch9/20.png',
        './images/math/8/ch9/21.png',
        './images/math/8/ch9/22.png',
        './images/math/8/ch9/23.png',
        './images/math/8/ch9/24.png',
        './images/math/8/ch9/25.png',] //ch9 is completed.
], // پایان کتاب ریاضی هشتم

[// کتاب ریاضی نهم
[  //فصل اول
    './images/math/9/ch1/1.png',
    './images/math/9/ch1/2.png',
    './images/math/9/ch1/3.png',
    './images/math/9/ch1/4.png',
    './images/math/9/ch1/5.png',
    './images/math/9/ch1/6.png',
    './images/math/9/ch1/7.png',
    './images/math/9/ch1/8.png',
    './images/math/9/ch1/9.png',
    './images/math/9/ch1/10.png',
    './images/math/9/ch1/11.png',
    './images/math/9/ch1/12.png',
    './images/math/9/ch1/13.png',
    './images/math/9/ch1/14.png',
    './images/math/9/ch1/15.png',
    './images/math/9/ch1/16.png',
    './images/math/9/ch1/17.png',
    './images/math/9/ch1/18.png',
    './images/math/9/ch1/19.png',
    './images/math/9/ch1/20.png',
    './images/math/9/ch1/21.png',
    './images/math/9/ch1/22.png',
    './images/math/9/ch1/23.png',
    './images/math/9/ch1/24.png',
    './images/math/9/ch1/25.png',
    './images/math/9/ch1/26.png',
    './images/math/9/ch1/27.png',
    './images/math/9/ch1/28.png',
    './images/math/9/ch1/29.png',
    './images/math/9/ch1/30.png',
    './images/math/9/ch1/31.png',
    './images/math/9/ch1/32.png',
    './images/math/9/ch1/33.png',
    './images/math/9/ch1/34.png',
    './images/math/9/ch1/35.png',], //ch1 is completed
[//فصل دوم
    './images/math/9/ch2/1.png',
    './images/math/9/ch2/2.png',
    './images/math/9/ch2/3.png',
    './images/math/9/ch2/4.png',
    './images/math/9/ch2/5.png',
    './images/math/9/ch2/6.png',
    './images/math/9/ch2/7.png',
    './images/math/9/ch2/8.png',
    './images/math/9/ch2/9.png',
    './images/math/9/ch2/10.png',
    './images/math/9/ch2/11.png',
    './images/math/9/ch2/12.png',
    './images/math/9/ch2/13.png',
    './images/math/9/ch2/14.png',
    './images/math/9/ch2/15.png',
    './images/math/9/ch2/16.png',
    './images/math/9/ch2/17.png',
    './images/math/9/ch2/18.png',
    './images/math/9/ch2/19.png',
    './images/math/9/ch2/20.png',
    './images/math/9/ch2/21.png',
    './images/math/9/ch2/22.png',
    './images/math/9/ch2/23.png',
    './images/math/9/ch2/24.png',
    './images/math/9/ch2/25.png',
    './images/math/9/ch2/26.png',
    './images/math/9/ch2/27.png',
    './images/math/9/ch2/28.png',
    './images/math/9/ch2/29.png',
    './images/math/9/ch2/30.png',
    './images/math/9/ch2/31.png',
    './images/math/9/ch2/32.png',
    './images/math/9/ch2/33.png',
    './images/math/9/ch2/34.png',
    './images/math/9/ch2/35.png',
    './images/math/9/ch2/36.png',
    './images/math/9/ch2/37.png',
    './images/math/9/ch2/38.png',
    './images/math/9/ch2/39.png',
    './images/math/9/ch2/40.png',], //ch2 is completed
[//فصل سوم
    './images/math/9/ch3/1.png',
    './images/math/9/ch3/2.png',
    './images/math/9/ch3/3.png',
    './images/math/9/ch3/4.png',
    './images/math/9/ch3/5.png',
    './images/math/9/ch3/6.png',
    './images/math/9/ch3/7.png',
    './images/math/9/ch3/8.png',
    './images/math/9/ch3/9.png',
    './images/math/9/ch3/10.png',
    './images/math/9/ch3/11.png',
    './images/math/9/ch3/12.png',
    './images/math/9/ch3/13.png',
    './images/math/9/ch3/14.png',
    './images/math/9/ch3/15.png',
    './images/math/9/ch3/16.png',
    './images/math/9/ch3/17.png',
    './images/math/9/ch3/18.png',
    './images/math/9/ch3/19.png',
    './images/math/9/ch3/20.png',
    './images/math/9/ch3/21.png',
    './images/math/9/ch3/22.png',
    './images/math/9/ch3/23.png',
    './images/math/9/ch3/24.png',
    './images/math/9/ch3/25.png',
    './images/math/9/ch3/26.png',
    './images/math/9/ch3/27.png',
    './images/math/9/ch3/28.png',
    './images/math/9/ch3/29.png',
    './images/math/9/ch3/30.png',
    './images/math/9/ch3/31.png',
    './images/math/9/ch3/32.png',
    './images/math/9/ch3/33.png',
    './images/math/9/ch3/34.png',
    './images/math/9/ch3/35.png',], //ch3 is completed
[//فصل چهارم
    './images/math/9/ch4/1.png',
    './images/math/9/ch4/2.png',
    './images/math/9/ch4/3.png',
    './images/math/9/ch4/4.png',
    './images/math/9/ch4/5.png',
    './images/math/9/ch4/6.png',
    './images/math/9/ch4/7.png',
    './images/math/9/ch4/8.png',
    './images/math/9/ch4/9.png',
    './images/math/9/ch4/10.png',
    './images/math/9/ch4/11.png',
    './images/math/9/ch4/12.png',
    './images/math/9/ch4/13.png',
    './images/math/9/ch4/14.png',
    './images/math/9/ch4/15.png',
    './images/math/9/ch4/16.png',
    './images/math/9/ch4/17.png',
    './images/math/9/ch4/18.png',
    './images/math/9/ch4/19.png',
    './images/math/9/ch4/20.png',
    './images/math/9/ch4/21.png',
    './images/math/9/ch4/22.png',
    './images/math/9/ch4/23.png',
    './images/math/9/ch4/24.png',
    './images/math/9/ch4/25.png',
    './images/math/9/ch4/26.png',
    './images/math/9/ch4/27.png',
    './images/math/9/ch4/28.png',
    './images/math/9/ch4/29.png',
    './images/math/9/ch4/30.png',
    './images/math/9/ch4/31.png',
    './images/math/9/ch4/32.png',
    './images/math/9/ch4/33.png',
    './images/math/9/ch4/34.png',
    './images/math/9/ch4/35.png',
    './images/math/9/ch4/36.png',
    './images/math/9/ch4/37.png',
    './images/math/9/ch4/38.png',
    './images/math/9/ch4/39.png',
    './images/math/9/ch4/40.png',
    './images/math/9/ch4/41.png',
    './images/math/9/ch4/42.png',
    './images/math/9/ch4/43.png',
    './images/math/9/ch4/44.png',
    './images/math/9/ch4/45.png',
    './images/math/9/ch4/46.png',], //ch4 is completed
[//فصل پنجم
    './images/math/9/ch5/1.png',
    './images/math/9/ch5/2.png',
    './images/math/9/ch5/3.png',
    './images/math/9/ch5/4.png',
    './images/math/9/ch5/5.png',
    './images/math/9/ch5/6.png',
    './images/math/9/ch5/7.png',
    './images/math/9/ch5/8.png',
    './images/math/9/ch5/9.png',
    './images/math/9/ch5/10.png',
    './images/math/9/ch5/11.png',
    './images/math/9/ch5/12.png',
    './images/math/9/ch5/13.png',
    './images/math/9/ch5/14.png',
    './images/math/9/ch5/15.png',
    './images/math/9/ch5/16.png',
    './images/math/9/ch5/17.png',
    './images/math/9/ch5/18.png',
    './images/math/9/ch5/19.png',
    './images/math/9/ch5/20.png',
    './images/math/9/ch5/21.png',
    './images/math/9/ch5/22.png',
    './images/math/9/ch5/23.png',
    './images/math/9/ch5/24.png',
    './images/math/9/ch5/25.png',
    './images/math/9/ch5/26.png',
    './images/math/9/ch5/27.png',
    './images/math/9/ch5/28.png',
    './images/math/9/ch5/29.png',
    './images/math/9/ch5/30.png',
    './images/math/9/ch5/31.png',
    './images/math/9/ch5/32.png',
    './images/math/9/ch5/33.png',
    './images/math/9/ch5/34.png',
    './images/math/9/ch5/35.png',
    './images/math/9/ch5/36.png',
    './images/math/9/ch5/37.png',
    './images/math/9/ch5/38.png',
    './images/math/9/ch5/39.png',
    './images/math/9/ch5/40.png',
    './images/math/9/ch5/41.png',
    './images/math/9/ch5/42.png',
    './images/math/9/ch5/43.png',
    './images/math/9/ch5/44.png',
    './images/math/9/ch5/45.png',
    './images/math/9/ch5/46.png',
    './images/math/9/ch5/47.png',
    './images/math/9/ch5/48.png',
    './images/math/9/ch5/49.png',
    './images/math/9/ch5/50.png',],  //ch5 is completed.
[//فصل ششم
    './images/math/9/ch6/1.png',
    './images/math/9/ch6/2.png',
    './images/math/9/ch6/3.png',
    './images/math/9/ch6/4.png',
    './images/math/9/ch6/5.png',
    './images/math/9/ch6/6.png',
    './images/math/9/ch6/7.png',
    './images/math/9/ch6/8.png',
    './images/math/9/ch6/9.png',
    './images/math/9/ch6/10.png',
    './images/math/9/ch6/11.png',
    './images/math/9/ch6/12.png',
    './images/math/9/ch6/13.png',
    './images/math/9/ch6/14.png',
    './images/math/9/ch6/15.png',
    './images/math/9/ch6/16.png',
    './images/math/9/ch6/17.png',
    './images/math/9/ch6/18.png',
    './images/math/9/ch6/19.png',
    './images/math/9/ch6/20.png',
    './images/math/9/ch6/21.png',
    './images/math/9/ch6/22.png',
    './images/math/9/ch6/23.png',
    './images/math/9/ch6/24.png',
    './images/math/9/ch6/25.png',
    './images/math/9/ch6/26.png',
    './images/math/9/ch6/27.png',
    './images/math/9/ch6/28.png',
    './images/math/9/ch6/29.png',
    './images/math/9/ch6/30.png',
    './images/math/9/ch6/31.png',
    './images/math/9/ch6/32.png',
    './images/math/9/ch6/33.png',
    './images/math/9/ch6/34.png',
    './images/math/9/ch6/35.png',
    './images/math/9/ch6/36.png',
    './images/math/9/ch6/37.png',
    './images/math/9/ch6/38.png',
    './images/math/9/ch6/39.png',
    './images/math/9/ch6/40.png',
    './images/math/9/ch6/41.png',
    './images/math/9/ch6/42.png',
    './images/math/9/ch6/43.png',
    './images/math/9/ch6/44.png',
    './images/math/9/ch6/45.png',
    './images/math/9/ch6/46.png',
    './images/math/9/ch6/47.png',], //ch6 is completed.
[//فصل هفتم
    './images/math/9/ch7/1.png',
    './images/math/9/ch7/2.png',
    './images/math/9/ch7/3.png',
    './images/math/9/ch7/4.png',
    './images/math/9/ch7/5.png',
    './images/math/9/ch7/6.png',
    './images/math/9/ch7/7.png',
    './images/math/9/ch7/8.png',
    './images/math/9/ch7/9.png',
    './images/math/9/ch7/10.png',
    './images/math/9/ch7/11.png',
    './images/math/9/ch7/12.png',
    './images/math/9/ch7/13.png',
    './images/math/9/ch7/14.png',
    './images/math/9/ch7/15.png',
    './images/math/9/ch7/16.png',
    './images/math/9/ch7/17.png',
    './images/math/9/ch7/18.png',
    './images/math/9/ch7/19.png',
    './images/math/9/ch7/20.png',
    './images/math/9/ch7/21.png',
    './images/math/9/ch7/22.png',
    './images/math/9/ch7/23.png',
    './images/math/9/ch7/24.png',
    './images/math/9/ch7/25.png',
    './images/math/9/ch7/26.png',
    './images/math/9/ch7/27.png',
    './images/math/9/ch7/28.png',
    './images/math/9/ch7/29.png',
    './images/math/9/ch7/30.png',
    './images/math/9/ch7/31.png',
    './images/math/9/ch7/32.png',
    './images/math/9/ch7/33.png',
    './images/math/9/ch7/34.png',
    './images/math/9/ch7/35.png',
    './images/math/9/ch7/36.png',
    './images/math/9/ch7/37.png',
    './images/math/9/ch7/38.png',
    './images/math/9/ch7/39.png',
    './images/math/9/ch7/40.png',
    './images/math/9/ch7/41.png',
    './images/math/9/ch7/42.png',
    './images/math/9/ch7/43.png',
    './images/math/9/ch7/44.png',
    './images/math/9/ch7/45.png',
    './images/math/9/ch7/46.png',
    './images/math/9/ch7/47.png',
    './images/math/9/ch7/48.png',
    './images/math/9/ch7/49.png',
    './images/math/9/ch7/50.png',
    './images/math/9/ch7/51.png',
    './images/math/9/ch7/52.png',
    './images/math/9/ch7/53.png',
    './images/math/9/ch7/54.png',
    './images/math/9/ch7/55.png',], //ch7 is completed.
[//فصل هشتم
    './images/math/9/ch8/1.png',
    './images/math/9/ch8/2.png',
    './images/math/9/ch8/3.png',
    './images/math/9/ch8/4.png',
    './images/math/9/ch8/5.png',
    './images/math/9/ch8/6.png',
    './images/math/9/ch8/7.png',
    './images/math/9/ch8/8.png',
    './images/math/9/ch8/9.png',
    './images/math/9/ch8/10.png',
    './images/math/9/ch8/11.png',
    './images/math/9/ch8/12.png',
    './images/math/9/ch8/13.png',
    './images/math/9/ch8/14.png',
    './images/math/9/ch8/15.png',
    './images/math/9/ch8/16.png',
    './images/math/9/ch8/17.png',
    './images/math/9/ch8/18.png',
    './images/math/9/ch8/19.png',
    './images/math/9/ch8/20.png',] //chp8 is completed.   
],//پایان کتاب نهم 
    //پایان درج سوالات سه کتاب:  14 اردیبهشت ماه 1403    
    //الحمدلله 
[//ریاضی دهم تجربی
[//فصل اول
    './images/math/10t/ch1/1.png',
    './images/math/10t/ch1/2.png',
    './images/math/10t/ch1/3.png',
    './images/math/10t/ch1/4.png',
    './images/math/10t/ch1/5.png',
    './images/math/10t/ch1/6.png',
    './images/math/10t/ch1/7.png',
    './images/math/10t/ch1/8.png',
    './images/math/10t/ch1/9.png',
    './images/math/10t/ch1/10.png',
    './images/math/10t/ch1/11.png',
    './images/math/10t/ch1/12.png',
    './images/math/10t/ch1/13.png',
    './images/math/10t/ch1/14.png',
    './images/math/10t/ch1/15.png',
    './images/math/10t/ch1/16.png',
    './images/math/10t/ch1/17.png',
    './images/math/10t/ch1/18.png',
    './images/math/10t/ch1/19.png',
    './images/math/10t/ch1/20.png',
    './images/math/10t/ch1/21.png',
    './images/math/10t/ch1/22.png',
    './images/math/10t/ch1/23.png',
    './images/math/10t/ch1/24.png',
    './images/math/10t/ch1/25.png',
    './images/math/10t/ch1/26.png',
    './images/math/10t/ch1/27.png',
    './images/math/10t/ch1/28.png',
    './images/math/10t/ch1/29.png',
    './images/math/10t/ch1/30.png',
    './images/math/10t/ch1/31.png',
    './images/math/10t/ch1/32.png',
    './images/math/10t/ch1/33.png',
    './images/math/10t/ch1/34.png',
    './images/math/10t/ch1/35.png',
    './images/math/10t/ch1/36.png',
    './images/math/10t/ch1/37.png',
    './images/math/10t/ch1/38.png',
    './images/math/10t/ch1/39.png',
    './images/math/10t/ch1/40.png',
    './images/math/10t/ch1/41.png',
    './images/math/10t/ch1/42.png',
    './images/math/10t/ch1/43.png',
    './images/math/10t/ch1/44.png',
    './images/math/10t/ch1/45.png',
    './images/math/10t/ch1/46.png',
    './images/math/10t/ch1/47.png',
    './images/math/10t/ch1/48.png',
    './images/math/10t/ch1/49.png',
    './images/math/10t/ch1/50.png',
    './images/math/10t/ch1/51.png',
    './images/math/10t/ch1/52.png',
    './images/math/10t/ch1/53.png',
    './images/math/10t/ch1/54.png',
    './images/math/10t/ch1/55.png',
    './images/math/10t/ch1/56.png',
],//پایان فصل اول- دهم تجربی
[// فصل دوم- دهم تجربی
    './images/math/10t/ch2/1.png',
    './images/math/10t/ch2/2.png',
    './images/math/10t/ch2/3.png',
    './images/math/10t/ch2/4.png',
    './images/math/10t/ch2/5.png',
    './images/math/10t/ch2/6.png',
    './images/math/10t/ch2/7.png',
    './images/math/10t/ch2/8.png',
    './images/math/10t/ch2/9.png',
    './images/math/10t/ch2/10.png',
    './images/math/10t/ch2/11.png',
    './images/math/10t/ch2/12.png',
    './images/math/10t/ch2/13.png',
    './images/math/10t/ch2/14.png',
    './images/math/10t/ch2/15.png',
    './images/math/10t/ch2/16.png',
    './images/math/10t/ch2/17.png',
    './images/math/10t/ch2/18.png',
    './images/math/10t/ch2/19.png',
    './images/math/10t/ch2/20.png',
    './images/math/10t/ch2/21.png',
    './images/math/10t/ch2/22.png',
    './images/math/10t/ch2/23.png',
    './images/math/10t/ch2/24.png',
    './images/math/10t/ch2/25.png',
    './images/math/10t/ch2/26.png',
    './images/math/10t/ch2/27.png',
    './images/math/10t/ch2/28.png',
],//پایان فصل دوم- ریاضی دهم تجربی
[//فصل سوم
    './images/math/10t/ch3/1.png',
    './images/math/10t/ch3/2.png',
    './images/math/10t/ch3/3.png',
    './images/math/10t/ch3/4.png',
    './images/math/10t/ch3/5.png',
    './images/math/10t/ch3/6.png',
    './images/math/10t/ch3/7.png',
    './images/math/10t/ch3/8.png',
    './images/math/10t/ch3/9.png',
    './images/math/10t/ch3/10.png',
    './images/math/10t/ch3/11.png',
    './images/math/10t/ch3/12.png',
    './images/math/10t/ch3/13.png',
    './images/math/10t/ch3/14.png',
    './images/math/10t/ch3/15.png',
    './images/math/10t/ch3/16.png',
    './images/math/10t/ch3/17.png',
    './images/math/10t/ch3/18.png',
    './images/math/10t/ch3/19.png',
    './images/math/10t/ch3/20.png',
    './images/math/10t/ch3/21.png',
    './images/math/10t/ch3/22.png',
    './images/math/10t/ch3/23.png',
    './images/math/10t/ch3/24.png',//تا ص 61 پایان درس3
  

],
],

[//ریاضی یازدهم تجربی
[//فصل اول
    './images/math/11t/ch1/1.png',
    './images/math/11t/ch1/2.png',
    './images/math/11t/ch1/3.png',
    './images/math/11t/ch1/4.png',
    './images/math/11t/ch1/5.png',
    './images/math/11t/ch1/6.png',
    './images/math/11t/ch1/7.png',
    './images/math/11t/ch1/8.png',
    './images/math/11t/ch1/9.png',
    './images/math/11t/ch1/10.png',
    './images/math/11t/ch1/11.png',
    './images/math/11t/ch1/12.png',
    './images/math/11t/ch1/13.png',
    './images/math/11t/ch1/14.png',
    './images/math/11t/ch1/15.png',
    './images/math/11t/ch1/16.png',
    './images/math/11t/ch1/17.png',
    './images/math/11t/ch1/18.png',
    './images/math/11t/ch1/19.png',
    './images/math/11t/ch1/20.png',
    './images/math/11t/ch1/21.png',
    './images/math/11t/ch1/22.png',
    './images/math/11t/ch1/23.png',
    './images/math/11t/ch1/24.png',
    './images/math/11t/ch1/25.png',
    './images/math/11t/ch1/26.png',
    './images/math/11t/ch1/27.png',
    './images/math/11t/ch1/28.png',
    './images/math/11t/ch1/29.png',
    './images/math/11t/ch1/30.png',
    './images/math/11t/ch1/31.png',
    './images/math/11t/ch1/32.png',
    './images/math/11t/ch1/33.png',
    './images/math/11t/ch1/34.png',
    './images/math/11t/ch1/35.png',
    './images/math/11t/ch1/36.png',
    './images/math/11t/ch1/37.png',
    './images/math/11t/ch1/38.png',
    './images/math/11t/ch1/39.png',
    './images/math/11t/ch1/40.png',
    './images/math/11t/ch1/41.png',
    './images/math/11t/ch1/42.png',
    './images/math/11t/ch1/43.png',
    './images/math/11t/ch1/44.png',
    './images/math/11t/ch1/45.png',
    './images/math/11t/ch1/46.png',
    './images/math/11t/ch1/47.png',
    './images/math/11t/ch1/48.png',
    './images/math/11t/ch1/49.png',
    './images/math/11t/ch1/50.png',
    './images/math/11t/ch1/51.png',
    './images/math/11t/ch1/52.png',
    './images/math/11t/ch1/53.png',
    './images/math/11t/ch1/54.png',
    './images/math/11t/ch1/55.png',
    './images/math/11t/ch1/56.png',
    './images/math/11t/ch1/57.png',
],//پایان فصل اول- ریاضی یازدهم تجربی
[//فصل دوم
    './images/math/11t/ch2/1.png',
    './images/math/11t/ch2/2.png',
    './images/math/11t/ch2/3.png',
    './images/math/11t/ch2/4.png',
    './images/math/11t/ch2/5.png',
    './images/math/11t/ch2/6.png',
    './images/math/11t/ch2/7.png',
    './images/math/11t/ch2/8.png',
    './images/math/11t/ch2/9.png',
    './images/math/11t/ch2/10.png',
    './images/math/11t/ch2/11.png',
    './images/math/11t/ch2/12.png',
    './images/math/11t/ch2/13.png',
    './images/math/11t/ch2/14.png',
    './images/math/11t/ch2/15.png',
    './images/math/11t/ch2/16.png',
    './images/math/11t/ch2/17.png',
    './images/math/11t/ch2/18.png',
    './images/math/11t/ch2/19.png',
    './images/math/11t/ch2/20.png',
    './images/math/11t/ch2/21.png',
    './images/math/11t/ch2/22.png',
    './images/math/11t/ch2/23.png',
    './images/math/11t/ch2/24.png',
    './images/math/11t/ch2/25.png',
    './images/math/11t/ch2/26.png',
    './images/math/11t/ch2/27.png',
    './images/math/11t/ch2/28.png',
    './images/math/11t/ch2/29.png',
    './images/math/11t/ch2/30.png',
    './images/math/11t/ch2/31.png',
    './images/math/11t/ch2/32.png',
    './images/math/11t/ch2/33.png',
    './images/math/11t/ch2/34.png',
    './images/math/11t/ch2/35.png',
    './images/math/11t/ch2/36.png',
    './images/math/11t/ch2/37.png',
    './images/math/11t/ch2/38.png',
    './images/math/11t/ch2/39.png',
],//پایان فصل دوم- یازدهم تجربی
[//فصل سوم
    './images/math/11t/ch3/1.png',
    './images/math/11t/ch3/2.png',
    './images/math/11t/ch3/3.png',
    './images/math/11t/ch3/4.png',
    './images/math/11t/ch3/5.png',
    './images/math/11t/ch3/6.png',
    './images/math/11t/ch3/7.png',
    './images/math/11t/ch3/8.png',
    './images/math/11t/ch3/9.png',
    './images/math/11t/ch3/10.png',
    './images/math/11t/ch3/11.png',
    './images/math/11t/ch3/12.png',
    './images/math/11t/ch3/13.png',
    './images/math/11t/ch3/14.png',// فصل 3 تا پایان درس1
],

],

[//ریاضی دوازدهم تجربی
[//فصل اول
    './images/math/12t/ch1/1.png',
    './images/math/12t/ch1/2.png',
    './images/math/12t/ch1/3.png',
    './images/math/12t/ch1/4.png',
    './images/math/12t/ch1/5.png',
    './images/math/12t/ch1/6.png',
    './images/math/12t/ch1/7.png',
    './images/math/12t/ch1/8.png', 
    './images/math/12t/ch1/9.png', 
    './images/math/12t/ch1/10.png', 
    './images/math/12t/ch1/11.png', 
    './images/math/12t/ch1/12.png', 
    './images/math/12t/ch1/13.png', 
    './images/math/12t/ch1/14.png', 
    './images/math/12t/ch1/15.png', 
    './images/math/12t/ch1/16.png', 
    './images/math/12t/ch1/17.png', 
    './images/math/12t/ch1/18.png', 
    './images/math/12t/ch1/19.png', 
    './images/math/12t/ch1/20.png', 
    './images/math/12t/ch1/21.png', 
    './images/math/12t/ch1/22.png', 
    './images/math/12t/ch1/23.png', 
    './images/math/12t/ch1/24.png', 
    './images/math/12t/ch1/25.png', 
    './images/math/12t/ch1/26.png', 
    './images/math/12t/ch1/27.png', 
    './images/math/12t/ch1/28.png', 
    './images/math/12t/ch1/29.png', 
    './images/math/12t/ch1/30.png', 
    './images/math/12t/ch1/31.png', 
    './images/math/12t/ch1/32.png', 
    './images/math/12t/ch1/33.png', 
    './images/math/12t/ch1/34.png', 
    './images/math/12t/ch1/35.png', 
    './images/math/12t/ch1/36.png', 
    './images/math/12t/ch1/37.png', 
    './images/math/12t/ch1/38.png', 
    './images/math/12t/ch1/39.png', 
],//پایان فص اول- دوازدهم تجربی
[//فصل دوم
    './images/math/12t/ch2/1.png', 
    './images/math/12t/ch2/2.png', 
    './images/math/12t/ch2/3.png', 
    './images/math/12t/ch2/4.png', 
    './images/math/12t/ch2/5.png', 
    './images/math/12t/ch2/6.png', 
    './images/math/12t/ch2/7.png', 
    './images/math/12t/ch2/8.png', 
    './images/math/12t/ch2/9.png', 
    './images/math/12t/ch2/10.png', 
    './images/math/12t/ch2/11.png', 
    './images/math/12t/ch2/12.png', 
    './images/math/12t/ch2/13.png', 
    './images/math/12t/ch2/14.png', 
    './images/math/12t/ch2/15.png', 
    './images/math/12t/ch2/16.png', 
    './images/math/12t/ch2/17.png', 
    './images/math/12t/ch2/18.png', 
    './images/math/12t/ch2/19.png', 
    './images/math/12t/ch2/20.png', 
    './images/math/12t/ch2/21.png', 
    './images/math/12t/ch2/22.png', 
    './images/math/12t/ch2/23.png', 
    './images/math/12t/ch2/24.png', 
    './images/math/12t/ch2/25.png', 
    './images/math/12t/ch2/26.png', 
    './images/math/12t/ch2/27.png', 
],//پایان فصل دوم- دوازدهم تجربی
[//فصل سوم
    './images/math/12t/ch3/1.png', 
    './images/math/12t/ch3/2.png', 
    './images/math/12t/ch3/3.png', 
    './images/math/12t/ch3/4.png', 
    './images/math/12t/ch3/5.png', 
    './images/math/12t/ch3/6.png', 
    './images/math/12t/ch3/7.png', 
    './images/math/12t/ch3/8.png', 
    './images/math/12t/ch3/9.png', 
    './images/math/12t/ch3/10.png', 
    './images/math/12t/ch3/11.png', 
    './images/math/12t/ch3/12.png', 
    './images/math/12t/ch3/13.png', 
    './images/math/12t/ch3/14.png', 
    './images/math/12t/ch3/15.png', 
    './images/math/12t/ch3/16.png', 
    './images/math/12t/ch3/17.png', 
    './images/math/12t/ch3/18.png', 
    './images/math/12t/ch3/19.png', 
    './images/math/12t/ch3/20.png', 
    './images/math/12t/ch3/21.png', 
    './images/math/12t/ch3/22.png', 
    './images/math/12t/ch3/23.png', 
    './images/math/12t/ch3/24.png', 
    './images/math/12t/ch3/25.png', 
    './images/math/12t/ch3/26.png', 
    './images/math/12t/ch3/27.png', 
    './images/math/12t/ch3/28.png', 
    './images/math/12t/ch3/29.png', 
    './images/math/12t/ch3/30.png', 
    './images/math/12t/ch3/31.png', 
    './images/math/12t/ch3/32.png', 
    './images/math/12t/ch3/33.png', 
    './images/math/12t/ch3/34.png', 
    './images/math/12t/ch3/35.png', 
    './images/math/12t/ch3/36.png', 
],//پایان فصل سوم- دوازدهم تجربی

],
[//دهم انسانی
[//فصل اول
    './images/math/10en/ch1/1.png',
    './images/math/10en/ch1/2.png',
    './images/math/10en/ch1/3.png',
    './images/math/10en/ch1/4.png',
    './images/math/10en/ch1/5.png',
    './images/math/10en/ch1/6.png',
    './images/math/10en/ch1/7.png',
    './images/math/10en/ch1/8.png',
    './images/math/10en/ch1/9.png',
    './images/math/10en/ch1/10.png',
    './images/math/10en/ch1/11.png',
    './images/math/10en/ch1/12.png',
    './images/math/10en/ch1/13.png',
    './images/math/10en/ch1/14.png',
    './images/math/10en/ch1/15.png',
    './images/math/10en/ch1/16.png',
    './images/math/10en/ch1/17.png',
    './images/math/10en/ch1/18.png',
    './images/math/10en/ch1/19.png',
    './images/math/10en/ch1/20.png',
    './images/math/10en/ch1/21.png',
    './images/math/10en/ch1/22.png',
    './images/math/10en/ch1/23.png',
    './images/math/10en/ch1/24.png',
    './images/math/10en/ch1/25.png',
    './images/math/10en/ch1/26.png',
    './images/math/10en/ch1/27.png',
    './images/math/10en/ch1/28.png',
    './images/math/10en/ch1/29.png',
    './images/math/10en/ch1/30.png',
    './images/math/10en/ch1/31.png',
    './images/math/10en/ch1/32.png',
    './images/math/10en/ch1/33.png',
    './images/math/10en/ch1/34.png',
    './images/math/10en/ch1/35.png',
    './images/math/10en/ch1/36.png',
    './images/math/10en/ch1/37.png',
    './images/math/10en/ch1/38.png',
    './images/math/10en/ch1/39.png',
    './images/math/10en/ch1/40.png',
    './images/math/10en/ch1/41.png',
    './images/math/10en/ch1/42.png',
    './images/math/10en/ch1/43.png',
    './images/math/10en/ch1/44.png',
    './images/math/10en/ch1/45.png',
    './images/math/10en/ch1/46.png',
    './images/math/10en/ch1/47.png',
    './images/math/10en/ch1/48.png',
    './images/math/10en/ch1/49.png',
],//پایان فصل اول- دهم انسانی
[//فصل دوم
    './images/math/10en/ch2/1.png',
    './images/math/10en/ch2/2.png',
    './images/math/10en/ch2/3.png',
    './images/math/10en/ch2/4.png',
    './images/math/10en/ch2/5.png',
    './images/math/10en/ch2/6.png',
    './images/math/10en/ch2/7.png',
    './images/math/10en/ch2/8.png',
    './images/math/10en/ch2/9.png',
    './images/math/10en/ch2/10.png',
    './images/math/10en/ch2/11.png',
    './images/math/10en/ch2/12.png',
    './images/math/10en/ch2/13.png',
    './images/math/10en/ch2/14.png',
    './images/math/10en/ch2/15.png',
    './images/math/10en/ch2/16.png',
    './images/math/10en/ch2/17.png',
    './images/math/10en/ch2/18.png',
    './images/math/10en/ch2/19.png',
    './images/math/10en/ch2/20.png',
    './images/math/10en/ch2/21.png',
    './images/math/10en/ch2/22.png',
    './images/math/10en/ch2/23.png',
    './images/math/10en/ch2/24.png',
    './images/math/10en/ch2/25.png',
    './images/math/10en/ch2/26.png',
    './images/math/10en/ch2/27.png',
    './images/math/10en/ch2/28.png',//پایان درس2 از فصل2- ص55
],
],
[//یازدهم انسانی
[//فصل اول
   './images/math/11en/ch1/1.png', 
   './images/math/11en/ch1/2.png', 
   './images/math/11en/ch1/3.png', 
   './images/math/11en/ch1/4.png', 
   './images/math/11en/ch1/5.png', 
   './images/math/11en/ch1/6.png', 
   './images/math/11en/ch1/7.png', 
   './images/math/11en/ch1/8.png', 
   './images/math/11en/ch1/9.png', 
   './images/math/11en/ch1/10.png', 
   './images/math/11en/ch1/11.png', 
   './images/math/11en/ch1/12.png', 
   './images/math/11en/ch1/13.png', 
   './images/math/11en/ch1/14.png', 
   './images/math/11en/ch1/15.png', 
   './images/math/11en/ch1/16.png', 
   './images/math/11en/ch1/17.png', 
   './images/math/11en/ch1/18.png', 
   './images/math/11en/ch1/19.png', 
   './images/math/11en/ch1/20.png', 
   './images/math/11en/ch1/21.png', 
   './images/math/11en/ch1/22.png', 
   './images/math/11en/ch1/23.png', 
   './images/math/11en/ch1/24.png', 
   './images/math/11en/ch1/25.png', 
   './images/math/11en/ch1/26.png', 
   './images/math/11en/ch1/27.png', 
   './images/math/11en/ch1/28.png', 
   './images/math/11en/ch1/29.png', 
   './images/math/11en/ch1/30.png', 
   './images/math/11en/ch1/31.png', 
   './images/math/11en/ch1/32.png', 
   './images/math/11en/ch1/33.png', 
   './images/math/11en/ch1/34.png', 
   './images/math/11en/ch1/35.png', 
],//پایان فصل اول- یازدهم انسانی
[//فصل دوم
   './images/math/11en/ch2/1.png', 
   './images/math/11en/ch2/2.png', 
   './images/math/11en/ch2/3.png', 
   './images/math/11en/ch2/4.png', 
   './images/math/11en/ch2/5.png', 
   './images/math/11en/ch2/6.png', 
   './images/math/11en/ch2/7.png', 
   './images/math/11en/ch2/8.png', 
   './images/math/11en/ch2/9.png', 
   './images/math/11en/ch2/10.png', 
   './images/math/11en/ch2/11.png', 
   './images/math/11en/ch2/12.png', 
   './images/math/11en/ch2/13.png', 
   './images/math/11en/ch2/14.png', 
   './images/math/11en/ch2/15.png', 
   './images/math/11en/ch2/16.png', 
   './images/math/11en/ch2/17.png', 
   './images/math/11en/ch2/18.png', 
   './images/math/11en/ch2/19.png', 
   './images/math/11en/ch2/20.png', 
   './images/math/11en/ch2/21.png', 
   './images/math/11en/ch2/22.png', 
   './images/math/11en/ch2/23.png', //تا درس1 صفحه 33
],
],
[//دوازدهم انسانی
[//فصل اول
    './images/math/12en/ch1/1.png', 
    './images/math/12en/ch1/2.png', 
    './images/math/12en/ch1/3.png', 
    './images/math/12en/ch1/4.png', 
    './images/math/12en/ch1/5.png', 
    './images/math/12en/ch1/6.png', 
    './images/math/12en/ch1/7.png', 
    './images/math/12en/ch1/8.png', 
    './images/math/12en/ch1/9.png', 
    './images/math/12en/ch1/10.png', 
    './images/math/12en/ch1/11.png', 
    './images/math/12en/ch1/12.png', 
    './images/math/12en/ch1/13.png', 
    './images/math/12en/ch1/14.png', 
    './images/math/12en/ch1/15.png', 
    './images/math/12en/ch1/16.png', 
    './images/math/12en/ch1/17.png', 
    './images/math/12en/ch1/18.png', 
    './images/math/12en/ch1/19.png', 
    './images/math/12en/ch1/20.png', 
    './images/math/12en/ch1/21.png', 
    './images/math/12en/ch1/22.png', 
    './images/math/12en/ch1/23.png', 
    './images/math/12en/ch1/24.png', 
    './images/math/12en/ch1/25.png', 
    './images/math/12en/ch1/26.png', 
    './images/math/12en/ch1/27.png', 
    './images/math/12en/ch1/28.png', 
    './images/math/12en/ch1/29.png', 
    './images/math/12en/ch1/30.png', 
    './images/math/12en/ch1/31.png', 
    './images/math/12en/ch1/32.png', 
    './images/math/12en/ch1/33.png', 
    './images/math/12en/ch1/34.png', 
    './images/math/12en/ch1/35.png', 
    './images/math/12en/ch1/36.png', 
    './images/math/12en/ch1/37.png', 
    './images/math/12en/ch1/38.png', 
    './images/math/12en/ch1/39.png', 
    './images/math/12en/ch1/40.png', 
    './images/math/12en/ch1/41.png', 
    './images/math/12en/ch1/42.png', 
    './images/math/12en/ch1/43.png', 
    './images/math/12en/ch1/44.png', 
    './images/math/12en/ch1/45.png', 
    './images/math/12en/ch1/46.png', 
    './images/math/12en/ch1/47.png', 
    './images/math/12en/ch1/48.png', 
    './images/math/12en/ch1/49.png', 
    './images/math/12en/ch1/50.png', 
    './images/math/12en/ch1/51.png', 
    './images/math/12en/ch1/52.png', 
    './images/math/12en/ch1/53.png', 
    './images/math/12en/ch1/54.png', 
    './images/math/12en/ch1/55.png', 
    './images/math/12en/ch1/56.png', 
    './images/math/12en/ch1/57.png', 
    './images/math/12en/ch1/58.png', 
    './images/math/12en/ch1/59.png', 
    './images/math/12en/ch1/60.png', 
    './images/math/12en/ch1/61.png', 
    './images/math/12en/ch1/62.png', 
    './images/math/12en/ch1/63.png', 
    './images/math/12en/ch1/64.png', 
    './images/math/12en/ch1/65.png', 
    './images/math/12en/ch1/66.png', 
    './images/math/12en/ch1/67.png', 
    './images/math/12en/ch1/68.png', 
    './images/math/12en/ch1/69.png', 
    './images/math/12en/ch1/70.png', 
    './images/math/12en/ch1/71.png', 
    './images/math/12en/ch1/72.png', 
    './images/math/12en/ch1/73.png', 
    './images/math/12en/ch1/74.png', 
    './images/math/12en/ch1/75.png', 
    './images/math/12en/ch1/76.png', 
    './images/math/12en/ch1/77.png', 
    './images/math/12en/ch1/78.png', 
    './images/math/12en/ch1/79.png', 
    './images/math/12en/ch1/80.png', 
    './images/math/12en/ch1/81.png', 
    './images/math/12en/ch1/82.png', 
    './images/math/12en/ch1/83.png', 
    './images/math/12en/ch1/84.png', 
    './images/math/12en/ch1/85.png', 
    './images/math/12en/ch1/86.png', 
    './images/math/12en/ch1/87.png', 
    './images/math/12en/ch1/88.png', 
    './images/math/12en/ch1/89.png', 
    './images/math/12en/ch1/90.png', 
    './images/math/12en/ch1/91.png', 
    './images/math/12en/ch1/92.png', 
    './images/math/12en/ch1/93.png', 
    './images/math/12en/ch1/94.png', 
    './images/math/12en/ch1/95.png', 
    './images/math/12en/ch1/96.png', 
    './images/math/12en/ch1/97.png', 
    './images/math/12en/ch1/98.png', 
    './images/math/12en/ch1/99.png', 
    './images/math/12en/ch1/100.png', 
    './images/math/12en/ch1/101.png', 
    './images/math/12en/ch1/102.png', 
    './images/math/12en/ch1/103.png', 
    './images/math/12en/ch1/104.png', 
    './images/math/12en/ch1/105.png', 
],//پایان فصل اول- دوازدهم انسانی

],
[//دهم کاردانش
[//پودمان اول
    './images/math/10kd/ch1/1.png',
    './images/math/10kd/ch1/2.png',
    './images/math/10kd/ch1/3.png',
    './images/math/10kd/ch1/4.png',
    './images/math/10kd/ch1/5.png',
    './images/math/10kd/ch1/6.png',
    './images/math/10kd/ch1/7.png',
    './images/math/10kd/ch1/8.png',
    './images/math/10kd/ch1/9.png',
    './images/math/10kd/ch1/10.png',
    './images/math/10kd/ch1/11.png',
    './images/math/10kd/ch1/12.png',
    './images/math/10kd/ch1/13.png',
    './images/math/10kd/ch1/14.png',
    './images/math/10kd/ch1/15.png',
    './images/math/10kd/ch1/16.png',
    './images/math/10kd/ch1/17.png',
    './images/math/10kd/ch1/18.png',
    './images/math/10kd/ch1/19.png',
    './images/math/10kd/ch1/20.png',
    './images/math/10kd/ch1/21.png',
    './images/math/10kd/ch1/22.png',
    './images/math/10kd/ch1/23.png',
    './images/math/10kd/ch1/24.png',
],//پایان پودمان اول

],
];

let sourcepack = [mathsource];
let gradenumber = -1;
let chapternumber = -1;
let gradename;
let qheight;

for (let i = 0; i < gradesbtn.length; i++) {
    gradesbtn[i].addEventListener('click', function () {
        clearlistquestions();
        clearformquestions();
        gradename = gradesbtn[i].textContent;
        inputwrapper[0].value = gradesbtn[i].innerHTML;
        selectedgrade.innerHTML = " پایه " + gradesbtn[i].innerHTML;
        gradenumber = i;
        if (i == 2) {
            chapter[8].style.display = "none";
        } else {
            chapter[8].style.display = "block";
        }
        gradesbtn[i].style.backgroundColor = "#42A5F5";
        for (let j = 0; j < gradesbtn.length; j++) {
            if (j != i) {
                gradesbtn[j].style.backgroundColor = "#F5F5F5";
            }
        }
        if (chapternumber != -1 && gradenumber != -1) {
            loadques(gradenumber, chapternumber);
        }
    })
}

for (let s = 0; s < chapter.length; s++) {
    chapter[s].addEventListener('click', function () {
        chapternumber = s;
        selectedchapter.innerHTML = chapter[s].innerHTML;
        main.style.marginRight = "0";
        chapter[s].style.backgroundColor = "#42A5F5";
        for (let j = 0; j < chapter.length; j++) {
            if (j != s) {
                chapter[j].style.backgroundColor = "#F5F5F5";
            }
        }
        clearlistquestions();
        if (chapternumber != -1 && gradenumber != -1) {
            loadques(gradenumber, chapternumber);
        }
    })
}


function loadques(gradenumber, chapternumber) {
    headerlowerelements.style.height = '350px';
    main.style.marginRight = "0";
    main.style.display = 'flex';
    for (let k = 0; k < mathsource[gradenumber][chapternumber].length; k++) {
        var newqlRow = qlist.insertRow();
        newqlRow.className = "qlrow";
        qlist.appendChild(newqlRow);
        var cell1 = newqlRow.insertCell();
        cell1.innerHTML = k + 1;
        plusq = document.createElement('div');
        plusq.className = "plus";
        plusq.title = "برای اضافه شدن این سؤال به فرم سؤالات، کلیک کنید.";
        cell1.appendChild(plusq);
        var cell2 = newqlRow.insertCell();
        cell2.className = 'lquestions';
        var imgl = document.createElement('img');
        imgl.className = 'limage';
        imgl.src = mathsource[gradenumber][chapternumber][k];
        plusq.addEventListener('click', function () {
            var newqfRow = qtable.insertRow();
            newqfRow.className = "qfrow";
            qtable.appendChild(newqfRow);
            var cell1 = newqfRow.insertCell();
            cell1.className = "questionnumber";
            cell1.style.position = "relative";
            b = document.createElement('button');
            cell1.appendChild(b);
            b.title = "حذف سؤال";
            var cell2 = newqfRow.insertCell();
            cell2.className = "questions";
            cell2.style.display = "flex"
            var imgq = document.createElement('img');
            imgq.className = "qimage";
            imgq.src = mathsource[gradenumber][chapternumber][k];
            cell2.appendChild(imgq);
            var cell3 = newqfRow.insertCell();
            cell3.className = "marks";
            cell3.style.position = "relative";
            var makeinput = document.createElement('input');
            makeinput.className = "markinput";
            cell3.appendChild(makeinput);
            b.addEventListener('click', function () {
                var row = this.parentNode.parentNode;
                var rowIndex = row.rowIndex;
                qtable.deleteRow(rowIndex);
            })
        })
        cell2.appendChild(imgl);
        
    }

}

numbering.addEventListener('click', function () {
    numbering_isclicked = true;
    let markinput = document.querySelectorAll('.markinput');
    let marks = document.querySelectorAll('.marks');
    for (i = 1; i < nums.length; i++) {
        nums[i].innerHTML = i;
    }
    for (i = 0; i < inputs.length; i++) {
        inputs[i].innerHTML = inputwrapper[i].value;
    }
    for (i = 0; i < markinput.length; i++) {
        marks[i+1].innerHTML = markinput[i].value;
    }
});

insertallquestions.addEventListener('click', function () {
    clearformquestions();
    set_sum();
    var w = document.querySelectorAll('.lquestions');
    var z = document.querySelectorAll('.questions');
    var imgl = document.querySelectorAll('.limage');
    for (var i = 0; i < w.length; i++) {
        var newqfRow = qtable.insertRow();
        newqfRow.className = 'qfrow';
        var cell1 = newqfRow.insertCell();
        cell1.className = "questionnumber";
        cell1.style.position = "relative";
        b = document.createElement('button');
        cell1.appendChild(b);
        b.title = "حذف سؤال";
        var cell2 = newqfRow.insertCell();
        cell2.className = "questions";
        var imgq = document.createElement('img');
        imgq.className = "qimage";
        imgq.src = imgl[i].src;
        cell2.appendChild(imgq);
        var cell3 = newqfRow.insertCell();
        cell3.className = "marks";
        cell3.style.position = "relative";
        var makeinput = document.createElement('input');
        makeinput.className = "markinput";
        cell3.appendChild(makeinput);
        b.addEventListener('click', function () {
            var row = this.parentNode.parentNode;
            var rowIndex = row.rowIndex;
            qtable.deleteRow(rowIndex);
        })
    }
    qtable.appendChild(newqfRow);
})

sendtoPDF.addEventListener('click', function () {
    let cloneNode =
    qtablewrapper.cloneNode(true);
    let printWindow = window.open('', '_blank');
    printWindow.document.write("<html><head><title></title>");
    printWindow.document.write("<link rel='stylesheet' type='text/css' href='./style.css'>");
    printWindow.document.write("</head><body>");
    printWindow.document.write(cloneNode.innerHTML);
    printWindow.document.write("</body></html>");
    printWindow.document.title = " آزمون ریاضی پایه " + gradename;
    printWindow.document.close();
    printWindow.onload = function(){
        printWindow.print();
        printWindow.close();
    };
});

clearall.addEventListener('click', function(){
    clearformquestions();
    set_sum();
});

function clearlistquestions() {
    for (i = 0; ; i++) {
        var row = document.querySelectorAll('.qlrow');
        if (row.length > 0) {
            qlist.deleteRow(1);
        }
        else { break; }
    }
}

function clearformquestions() {
    for (i = 0; ; i++) {
        var row = document.querySelectorAll('.qfrow');
        if (row.length > 0) {
            qtable.deleteRow(1);
        }
        else { break; }
    }
    for (var i = 0; i < inputs.length; i++) {
        inputs[i].innerHTML = "";
    }
    npages.innerHTML = "";
}

